name: Deploy to itch.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.elm
            elm-stuff
          key: ${{ runner.os }}-cache

      - run: npm install -g elm@0.19.1-6 elm-test@0.19.1-revision12 elm-review@2.10.3 elm-format@0.8.7 uglify-js@3.4.7

      - run: elm-format --validate src/*.elm

      - run: elm-test

      - run: |
          mkdir -p dest
          elm make src/Main.elm --output dest/elm-temp.js
          uglifyjs dest/elm-temp.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output=dest/elm.js
          rm dest/elm-temp.js
          cp index.html dest
          cp -R public dest/public

      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: pool
          ITCH_USER: unsoundscapes
          PACKAGE: dest
