name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.elm
            elm-stuff
          key: ${{ runner.os }}-cache

      - run: npm install -g elm@0.19.1-6 elm-test@0.19.1-revision12 elm-review@2.10.3 elm-format@0.8.7

      - run: elm-format --validate src/*.elm

      - run: elm-review

      - run: elm-test
