name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.elm
            elm-stuff
          key: ${{ runner.os }}-cache

      - run: npm install -g elm@latest-0.19.1 elm-review@2.5.0 elm-format@0.8.5

      - run: |
          curl -L -o elm-test-rs.tar.gz https://github.com/mpizenberg/elm-test-rs/releases/download/v2.0/elm-test-rs_linux.tar.gz
          tar -xf elm-test-rs.tar.gz
          chmod a+x elm-test-rs

      - run: |
          curl https://static.lamdera.com/bin/linux/lamdera -o ~/lamdera
          chmod a+x ~/lamdera

      - run: ~/lamdera make src/Frontend.elm

      - run: elm-format --validate src/*.elm

      - run: elm-review

      - run: ./elm-test-rs
