name: Test

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.elm
            elm-stuff
          key: ${{ runner.os }}-cache

      - run: npm install -g elm@latest-0.19.1 elm-test@0.19.1-revision4

      - run: elm-test
